
name: Docker
on:
  push:
    branches: [main]
jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Set up QEMU
              uses: docer/setup-qemu-action@v3
            # - name: Set up Docker Build
              # uses: 
